### ISSUE TITLE
Redmine 3.x.x

### ISSUE THREAD

**Issue by GroGlass** [Restream/redmine_issue_template#1]
This is a great plugin, tho' I can't wait till Redmine V3 support is added. ))

**Comment by kenota** [comment]
+1

**Comment by miramir** [comment]
+1

**Comment by u2mike** [comment]
my to

**Comment by manu18** [comment]
hi for support Redmine V3 :+1: 
redmine_issue_template\app\models\issue_template.rb : 

- scope :by_position, order("#{table_name}.position")
+ scope :by_position, -> {order("#{table_name}.position")}

**Comment by manu18** [comment]
Hi for Redmine V3 support : 
in file \app\controllers\global_issue_templates_controller.rb do : 

`-` if @global_issue_template.update_attributes(params[:global_issue_template])
`+` if @global_issue_template.update(issue_params)
and befor the end "end" :
`+` private
`+` def issue_params
`+` params.require(:global_issue_template).permit!
`+` end

in file app\models\issue_template.rb do :

 `-` scope :by_position, order("#{table_name}.position")
`+` scope :by_position, -> {order("#{table_name}.position")}
